Last login: Wed Jun 20 10:11:19 on console
e1z2r8p2% vim 02_daenerys.py
e1z2r8p2% python 02_daemeerys.py
python: can't open file '02_daemeerys.py': [Errno 2] No such file or directory
e1z2r8p2% python 02_daemerys.py 
python: can't open file '02_daemerys.py': [Errno 2] No such file or directory
e1z2r8p2% python 02_daenerys.py
  File "02_daenerys.py", line 4
    print ("Welcome, Daenerys.")
        ^
SyntaxError: invalid syntax
e1z2r8p2% vim 02_daenerys.py    
e1z2r8p2% python 02_daenerys.py
  File "02_daenerys.py", line 7
    else
       ^
SyntaxError: invalid syntax
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
  File "02_daenerys.py", line 7
    else input == (" ")
             ^
SyntaxError: invalid syntax
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
  File "02_daenerys.py", line 7
    else
       ^
SyntaxError: invalid syntax
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
Who goes there?
Move along, now.
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
Who goes there?
Move along, now.
e1z2r8p2% hi
zsh: command not found: hi
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% vim 01_player.py  
e1z2r8p2% vim 02_daenerys.py
e1z2r8p2% python 02_daenerys.py
Who goes there?
 chris
Traceback (most recent call last):
  File "02_daenerys.py", line 2, in <module>
    name = input (" ")
  File "<string>", line 1, in <module>
NameError: name 'chris' is not defined
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
Who goes there?
 Chris
Move along, now.
e1z2r8p2% python 02_daenerys.py
Who goes there?
 Dany
Move along, now.
e1z2r8p2% vim 02_daenerys.py   
e1z2r8p2% python 02_daenerys.py
Who goes there?
 Dany
Dany who?
e1z2r8p2% python 02_daenerys.py
Who goes there?
 DHTFHNUQARFMQMKGSPRLRSKBCMD
Welcome, Daenerys.
e1z2r8p2% vim 02_daenerys.py   

print ("Who goes there?")
name = raw_input (" ")
if name == 'DHTFHNUQARFMQMKGSPRLRSKBCMD':
        print ("Welcome, Daenerys.")
elif name == 'Dany':
        print ("Dany who?")
else :
        print ("Move along, now.")
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
02_daenerys.py                                                8,34           All
"02_daenerys.py" 8L, 219C
